### ISSUE TITLE
Does not properly with with vim-licenses

### ISSUE THREAD

**Issue by kozross** [dunedain289/vim-tup#1]
I've raised this issue with [the affected project][1], and they have responded, but as I don't know about syntax files, I'm not sure how to fix it myself. Would you be able to patch this?

[1]: https://github.com/antoyo/vim-licenses/issues/14

**Comment by dunedain289** [comment]
Looks like you'll need to add a line like `set comments=:#` to either the `syntax/tup.vim` or `ftdetect/tup.vim`. I'm not real clear on the exact variable rules for Vim, so please try a few things and open a Pull Request if you find something that works.
